# Generated by Django 3.1.2 on 2022-04-09 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('role', models.CharField(choices=[('Elementary', 'Elementary'), ('Secondary', 'Secondary'), ('All', 'All'), ('Others', 'Others')], max_length=200, null=True)),
                ('subject', models.CharField(choices=[('English', 'English'), ('Math', 'Math'), ('Science', 'Science'), ('Japanese', 'Japanese'), ('History', 'History'), ('Computer Science', 'Computer Science'), ('Others', 'Others')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('room', models.CharField(max_length=200, null=True)),
                ('day', models.PositiveSmallIntegerField(null=True)),
                ('period', models.PositiveSmallIntegerField(null=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='substitute.teacher')),
            ],
        ),
    ]
