# Generated by Django 3.1.2 on 2022-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0002_auto_20220409_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
