# Generated by Django 3.1.2 on 2022-04-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0003_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
