# Generated by Django 3.1.2 on 2022-04-09 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0004_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Elementary', 'Elementary'), ('Secondary', 'Secondary'), ('All', 'All'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('Math', 'Math'), ('Science', 'Science'), ('Japanese', 'Japanese'), ('History', 'History'), ('Computer Science', 'Computer Science'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
