# Generated by Django 3.1.2 on 2022-04-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0005_auto_20220409_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstituteSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
