# Generated by Django 3.1.2 on 2022-05-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0008_auto_20220415_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedule_uploaded',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
