# Generated by Django 3.1.2 on 2022-05-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0009_user_schedule_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='schedule_uploaded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
