# Generated by Django 4.0.4 on 2022-05-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0011_auto_20220523_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='schedule_uploaded',
        ),
    ]
