# Generated by Django 4.0.4 on 2022-05-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0013_alter_lesson_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
