# Generated by Django 4.0.4 on 2022-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0015_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
