# Generated by Django 4.0.4 on 2022-05-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0016_holiday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='end',
            field=models.DateField(null=True),
        ),
    ]
