# Generated by Django 3.1.2 on 2022-09-04 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0017_alter_holiday_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='year',
        ),
        migrations.RemoveField(
            model_name='substituteschedule',
            name='lunch_recess',
        ),
        migrations.AddField(
            model_name='substituteschedule',
            name='lunch_one',
            field=models.ManyToManyField(blank=True, related_name='lunch_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='substituteschedule',
            name='lunch_three',
            field=models.ManyToManyField(blank=True, related_name='lunch_three', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='substituteschedule',
            name='lunch_two',
            field=models.ManyToManyField(blank=True, related_name='lunch_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='period',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
