# Generated by Django 3.1.2 on 2022-09-04 07:49

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0018_auto_20220904_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Elementary', 'Elementary'), ('Middle', 'Middle'), ('High', 'High')], max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Math', 'Math'), ('Science', 'Science'), ('Japanese', 'Japanese'), ('Spanish', 'Spanish'), ('French', 'French'), ('Computer Science', 'Computer Science')], max_length=61, null=True),
        ),
    ]
