# Generated by Django 3.1.2 on 2022-09-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0019_auto_20220904_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
