# Generated by Django 4.0.6 on 2022-10-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0021_substitute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='count',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
